site_name: Indico tanulása
theme:
    language: hu
    name: material
    font: false
    features:
        - content.code.copy
        - content.action.edit
        - content.action.view
        - navigation.footer
    palette:
        # Palette toggle for light mode
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
repo_name: 'vzsi/indico-user-docs-hu'
repo_url: 'https://github.com/vzsi/indico-user-docs-hu'
markdown_extensions:
    - admonition
extra_css:
    - stylesheets/fonts.css
    - stylesheets/extra.css
nav:
    - Bevezetés: index.md
    - Kategóriák:
        - Bevezetés: categories/about.md
        - Kategória létrehozása: categories/creating.md
        - Áttekintés: categories/overview.md
        - Egy kategória kezelése:
            - Bevezetés: categories/managing.md
            - Védelem: categories/protection.md
            - Moderálás: categories/moderation.md
            - Naplózás: categories/logging.md
    - Események kezelése:
        - Bevezetés az eseményekbe: events.md
        - Előadások:
            - Bevezetés: lectures/about.md
            - Előadás létrehozása: lectures/creating.md
            - Anyag hozzáadása egy előadáshoz: lectures/material.md
        - Találkozók:
            - Bevezetés: meetings/about.md
            - Megbeszélés létrehozása: meetings/creating.md
            - Ütemterv készítése: meetings/timetable.md
            - Jegyzőkönyv hozzáadása egy értekezlethez: meetings/minutes.md
            - Anyag hozzáadása egy értekezlethez: meetings/material.md
        - Konferenciák:
            - Bevezetés: conferences/about.md
            - A program meghatározása: conferences/programme.md
            - Absztraktfelhívás: conferences/cfa.md
            - Absztrakt benyújtása: conferences/submitting.md
            - Absztraktok elbírálása: conferences/reviewing.md
            - Az ülések kezelése: conferences/sessions.md
            - Ütemterv készítése: conferences/timetable.md
            - A regisztrációs folyamat konfigurálása: conferences/registration_config.md
            - Regisztráció a konferencián: conferences/registration.md
            - A konferencia menüjének testreszabása: conferences/custom_menu.md
            - A konferenciaoldal elrendezésének testreszabása: conferences/custom_layout.md
            - Előadások áttekintése:
                - Bevezetés: conferences/papers/introduction.md
                - Papírok szakértői értékelése: conferences/papers/peer_reviewing.md
                - Szerkesztés: conferences/papers/editing.md
            - Programkódok: conferences/programme_codes.md
            - Emberek kezelése: conferences/people.md
        - Adatvédelem: privacy.md
        - Eseménysorozatok: event_series.md
    - Helyiségfoglalás:
        - Bevezetés: room_booking/about.md
        - A modul elérése: room_booking/accessing.md
        - Szobafoglalás: room_booking/booking.md
        - Keresés és foglalás: room_booking/search_and_book.md
        - A foglalások megtekintése: room_booking/viewing_bookings.md
        - Szobák blokkolása: room_booking/blocking.md
        - A funkciókészlet összefoglalása: room_booking/features.md
        - Fogalomtár: room_booking/glossary.md
    - Eseményfelmérések:
        - Bevezetés: surveys/about.md
        - Felmérés beállítása: surveys/setup.md
        - Felmérés megnyitása/zárása: surveys/opening.md
    - Egyéb funkciók:
        - Emlékeztetők: reminders.md
        - Importálás a naptárkészítő eszközökbe: calendar_import.md
        - Egyéni szerepek használata: custom_roles.md
    - Pluginok:
        - Zoom: plugins/zoom.md
    - GYIK: faq.md
